# Generated by Django 2.2.1 on 2019-05-14 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_report_id', models.CharField(max_length=1)),
                ('transaction_code', models.CharField(blank=True, max_length=1)),
                ('election_year', models.IntegerField(null=True)),
                ('transaction_id', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('date_original', models.DateField(null=True)),
                ('contributor_code', models.CharField(blank=True, max_length=6)),
                ('contribution_type', models.CharField(blank=True, max_length=1)),
                ('corporation_name', models.TextField(blank=True)),
                ('contributor_first_name', models.TextField(blank=True)),
                ('contributor_mid_initial', models.CharField(blank=True, max_length=1)),
                ('contributor_last_name', models.TextField(blank=True)),
                ('contributor_address', models.TextField(blank=True)),
                ('contributor_city', models.TextField(blank=True)),
                ('contributor_state', models.CharField(blank=True, max_length=2)),
                ('contributor_zip', models.CharField(blank=True, max_length=10)),
                ('check_number', models.TextField(blank=True)),
                ('check_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('amount_additional', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('other_receipt_code', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('transfer_type', models.CharField(blank=True, max_length=1)),
                ('checkbox', models.CharField(blank=True, max_length=1)),
                ('user_id', models.CharField(blank=True, max_length=8)),
                ('record_creation_datetime', models.DateTimeField(null=True)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nys.Filer')),
                ('purpose_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nys.Purpose')),
                ('purpose_code_q', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_report', to='nys.Purpose')),
            ],
        ),
    ]
