# Generated by Django 2.2.1 on 2019-05-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0002_purpose_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='transaction_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
