# Generated by Django 2.2.1 on 2019-05-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0006_auto_20190515_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filer',
            name='office_id_lk',
        ),
    ]
