# Generated by Django 2.2.1 on 2019-05-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0007_remove_filer_office_id_lk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filer',
            old_name='filer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='filer',
            old_name='filer_status',
            new_name='status',
        ),
    ]
