# Generated by Django 2.2.1 on 2019-05-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0008_auto_20190515_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyfiler',
            name='county',
        ),
    ]
