# Generated by Django 2.2.1 on 2019-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0009_remove_countyfiler_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='subdivision',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CountyFiler',
        ),
    ]
