# Generated by Django 2.2.1 on 2019-05-15 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nys', '0010_auto_20190515_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='filer',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nys.Municipality'),
        ),
    ]
